repository : schema.sql objects.sql
	psql postgres --file="schema.sql"
	#bash plsh_functions.sh
	psql postgres --file="objects.sql"
	#psql postgres --file="fk_create.sql"
	#psql postgres --file="logic.sql"
